server:
  port: 9090
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://47.92.204.214:5602;database=DORUN_LIFE;integratedSecurity=false
    username: sa
    password: Dorun123456
    druid:
      initial-size: 8
      min-idle: 1
      max-active: 20
      max-wait: 60000
      time-between-eviction-runsMillis: 60000
      min-evictable-idle-timeMillis: 300000
      validation-query: select 'x' FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      use-global-data-source-stat: true
web-service:
  target: http://111.8.122.87:2017/WebServiceBank.asmx
pay-type:
  wechat: 微信发票
  alipay: 支付宝发票
logging:
  path: /Volumes/code/log
  level:
    org.springframework.web: DEBUG
    com.core: DEBUG
netty:
  address: 127.0.0.1
  port: 9020
txt:
  path: /Volumes/code/product/